name: daily-report

on:
  schedule:
    - cron: '0 23 * * 0-4'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: run daily report
        env:
          FTQQ_SENDKEY: ${{ secrets.FTQQ_SENDKEY }}
        run: python daily_report.py
